const fs = require('fs');
const html = fs.readFileSync('scratch/strota_rendered.html', 'utf8');
const target = 'class="quantity-selector-wrapper"';
const idx = html.indexOf(target);
console.log('--- BEFORE 2000 ---');
console.log(html.substring(idx - 2500, idx - 1500));
console.log('--- BEFORE 1000 ---');
console.log(html.substring(idx - 1500, idx));
console.log('--- AFTER 1200-2200 ---');
console.log(html.substring(idx + 1200, idx + 2200));
